a = int(input())
b = int(input())
c = int(input())
multiply = a*b*c
list_multi = list(map(int,str(multiply)))
print(list_multi.count(0))
print(list_multi.count(1))
print(list_multi.count(2))
print(list_multi.count(3))
print(list_multi.count(4))
print(list_multi.count(5))
print(list_multi.count(6))
print(list_multi.count(7))
print(list_multi.count(8))
print(list_multi.count(9))